### ISSUE TITLE
Some issues after testing Go Cardless

### ISSUE THREAD

**Issue by madurak** [veda-consulting/uk.co.vedaconsulting.payment.gocardlessdd#5]
Hi, 
Came across a few issues, can you take a look into these please?

1) Collection date details are not filled up (preferred collection and first collection)
2) Civi contribution status is Completed, but in Go Cardless it is Pending ( its at 'Payment submission requested' state, see attached)
3) Fee amount and Net amount are incorrect.

<img width="749" alt="issue_1" src="https://cloud.githubusercontent.com/assets/10810117/9543889/6aaa55ec-4d74-11e5-9a0c-85e6b290252a.png">
<img width="714" alt="issue_1 1" src="https://cloud.githubusercontent.com/assets/10810117/9543893/6fe727ba-4d74-11e5-9aa0-91ea9ab76a01.png">
![issue_2 3](https://cloud.githubusercontent.com/assets/10810117/9543898/77e94aa6-4d74-11e5-8149-f261bcd40082.png)
![issue_3](https://cloud.githubusercontent.com/assets/10810117/9543903/7ed02998-4d74-11e5-8e00-ea7f32369fa8.png)

Kind Regards,
Madura

**Comment by natsukipope** [comment]
Hello, just wondering if there's any updates on this issue. We have another client who would like to migrate to Go Cardless and on Civi 4.6.x. 

Thank you,
Natsuki

**Comment by veda-consulting** [comment]
@natsukipope These issues have been addressed we believe, could you test and confirm. We also have tested on 4.6 and all looks ok but again please test and confirm.

**Comment by madurak** [comment]
I am afraid we are still having the problem with the status on Contribution. In Go Cardless there are several stages before a payment goes to the merchant, and at first it is Pending, but in Civi contribution, the status says Completed.
We pulled the latest changes for gocardless extension (and direct debit extension) and get a backtrace error on confirming the payment.
<img width="1397" alt="screen shot 2015-11-26 at 09 02 12" src="https://cloud.githubusercontent.com/assets/10810117/11419056/dcec874e-941c-11e5-8ad6-bb5cd11f1a79.png">

This is on 4.6.8

-Madura

**Comment by Kajakaran** [comment]
Hi @madurak 

It looks like you have not ticked recurring check box in contribution page. This should be checked as part of direct debit payment so that recurring record will be created in CiviCRM.

![recur_tick](https://cloud.githubusercontent.com/assets/7429798/11420044/66115652-9423-11e5-98ff-d6e4001b33a6.png)

In regards to contribution status, we normally mark as completed in the first place. Once actual payment comes in then depend on the payment, we have to mark either completed or failed.

Thanks
Kajan

cc - @veda-consulting
